// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqrvskldidbjpuweuoft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxcnZza2xkaWRianB1d2V1b2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NzAwOTQsImV4cCI6MjA1NDA0NjA5NH0.L1UBX8-r6F_BsB037u0HPHjcsm-KF0gi1oPR3wzE5-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);